[package]
name = "gpui-tetris"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
license = "MIT"

[dependencies]
gpui = { version = "0.2.2", features = ["runtime_shaders"] }
cpal = "0.18.1"
crossbeam-channel = "0.5.16"
hound = "3.5.1"
anyhow = "1.0.104"
gilrs = "0.11.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
semver = "1.0.28"

[package.metadata.bundle]
name = "gpui-tetris"
identifier = "com.lyuguoning.com.gpui-tetris"
icon = ["assets/icon.icns"]
resources = ["assets/sfx"]
